### ISSUE TITLE
Assign Authors Existing user dropdown freezes on WooCommerce store with 10,000+ customer accounts

### ISSUE THREAD

**Issue by dashmurphy** [WordPress/wordpress-importer#108] opened 2021-09-14 14:03 UTC
The existing users dropdown should only pull users with the Author role or higher.  Or specifically just not pull users with the WooCommerce role of customer since it really doesn't make sense to assign them as an author of anything.

**Comment by dd32** [comment] 2022-10-10 06:03
Closing this as a duplicate of #34.

**Closed by dd32** 2022-10-10 06:03 UTC
Labels: [Status] Duplicate
